/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BotMessage } from "./models/botMessage";
import { UserInputAction } from "./models/userInputAction";
import { Message } from "./models/message";
import { BotMessage as BotMessage1, Message as Message1 } from "./components";
import { UserMessage } from "./models/userMessage";
export { BotMessage } from "./models/botMessage";
export { UserInputAction } from "./models/userInputAction";
export { Message } from "./models/message";
export { BotMessage as BotMessage1, Message as Message1 } from "./components";
export { UserMessage } from "./models/userMessage";
export namespace Components {
    interface BotChatMessage {
        "isLast": boolean;
        "message": BotMessage;
    }
    interface ChatFab {
    }
    interface ChatInput {
    }
    interface ChatMessages {
        "messages": Message[];
    }
    interface HumaineChatbot {
        "apiKey": string;
        "assetsPath": string;
        "baseUrl": string;
        "langCode": string;
    }
    interface SystemChatMessage {
        "message": Message1;
    }
    interface UserChatMessage {
        "message": UserMessage;
    }
}
export interface BotChatMessageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBotChatMessageElement;
}
export interface ChatFabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChatFabElement;
}
export interface ChatInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChatInputElement;
}
export interface ChatMessagesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChatMessagesElement;
}
declare global {
    interface HTMLBotChatMessageElementEventMap {
        "feedbackGiven": BotMessage;
    }
    interface HTMLBotChatMessageElement extends Components.BotChatMessage, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBotChatMessageElementEventMap>(type: K, listener: (this: HTMLBotChatMessageElement, ev: BotChatMessageCustomEvent<HTMLBotChatMessageElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBotChatMessageElementEventMap>(type: K, listener: (this: HTMLBotChatMessageElement, ev: BotChatMessageCustomEvent<HTMLBotChatMessageElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBotChatMessageElement: {
        prototype: HTMLBotChatMessageElement;
        new (): HTMLBotChatMessageElement;
    };
    interface HTMLChatFabElementEventMap {
        "chatFabPressed": any;
    }
    interface HTMLChatFabElement extends Components.ChatFab, HTMLStencilElement {
        addEventListener<K extends keyof HTMLChatFabElementEventMap>(type: K, listener: (this: HTMLChatFabElement, ev: ChatFabCustomEvent<HTMLChatFabElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLChatFabElementEventMap>(type: K, listener: (this: HTMLChatFabElement, ev: ChatFabCustomEvent<HTMLChatFabElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLChatFabElement: {
        prototype: HTMLChatFabElement;
        new (): HTMLChatFabElement;
    };
    interface HTMLChatInputElementEventMap {
        "inputActionSubmitted": UserInputAction;
        "focusChanged": boolean;
    }
    interface HTMLChatInputElement extends Components.ChatInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLChatInputElementEventMap>(type: K, listener: (this: HTMLChatInputElement, ev: ChatInputCustomEvent<HTMLChatInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLChatInputElementEventMap>(type: K, listener: (this: HTMLChatInputElement, ev: ChatInputCustomEvent<HTMLChatInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLChatInputElement: {
        prototype: HTMLChatInputElement;
        new (): HTMLChatInputElement;
    };
    interface HTMLChatMessagesElementEventMap {
        "feedbackReceived": BotMessage1;
    }
    interface HTMLChatMessagesElement extends Components.ChatMessages, HTMLStencilElement {
        addEventListener<K extends keyof HTMLChatMessagesElementEventMap>(type: K, listener: (this: HTMLChatMessagesElement, ev: ChatMessagesCustomEvent<HTMLChatMessagesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLChatMessagesElementEventMap>(type: K, listener: (this: HTMLChatMessagesElement, ev: ChatMessagesCustomEvent<HTMLChatMessagesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLChatMessagesElement: {
        prototype: HTMLChatMessagesElement;
        new (): HTMLChatMessagesElement;
    };
    interface HTMLHumaineChatbotElement extends Components.HumaineChatbot, HTMLStencilElement {
    }
    var HTMLHumaineChatbotElement: {
        prototype: HTMLHumaineChatbotElement;
        new (): HTMLHumaineChatbotElement;
    };
    interface HTMLSystemChatMessageElement extends Components.SystemChatMessage, HTMLStencilElement {
    }
    var HTMLSystemChatMessageElement: {
        prototype: HTMLSystemChatMessageElement;
        new (): HTMLSystemChatMessageElement;
    };
    interface HTMLUserChatMessageElement extends Components.UserChatMessage, HTMLStencilElement {
    }
    var HTMLUserChatMessageElement: {
        prototype: HTMLUserChatMessageElement;
        new (): HTMLUserChatMessageElement;
    };
    interface HTMLElementTagNameMap {
        "bot-chat-message": HTMLBotChatMessageElement;
        "chat-fab": HTMLChatFabElement;
        "chat-input": HTMLChatInputElement;
        "chat-messages": HTMLChatMessagesElement;
        "humaine-chatbot": HTMLHumaineChatbotElement;
        "system-chat-message": HTMLSystemChatMessageElement;
        "user-chat-message": HTMLUserChatMessageElement;
    }
}
declare namespace LocalJSX {
    interface BotChatMessage {
        "isLast"?: boolean;
        "message"?: BotMessage;
        "onFeedbackGiven"?: (event: BotChatMessageCustomEvent<BotMessage>) => void;
    }
    interface ChatFab {
        "onChatFabPressed"?: (event: ChatFabCustomEvent<any>) => void;
    }
    interface ChatInput {
        "onFocusChanged"?: (event: ChatInputCustomEvent<boolean>) => void;
        "onInputActionSubmitted"?: (event: ChatInputCustomEvent<UserInputAction>) => void;
    }
    interface ChatMessages {
        "messages"?: Message[];
        "onFeedbackReceived"?: (event: ChatMessagesCustomEvent<BotMessage1>) => void;
    }
    interface HumaineChatbot {
        "apiKey"?: string;
        "assetsPath"?: string;
        "baseUrl"?: string;
        "langCode"?: string;
    }
    interface SystemChatMessage {
        "message"?: Message1;
    }
    interface UserChatMessage {
        "message"?: UserMessage;
    }
    interface IntrinsicElements {
        "bot-chat-message": BotChatMessage;
        "chat-fab": ChatFab;
        "chat-input": ChatInput;
        "chat-messages": ChatMessages;
        "humaine-chatbot": HumaineChatbot;
        "system-chat-message": SystemChatMessage;
        "user-chat-message": UserChatMessage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bot-chat-message": LocalJSX.BotChatMessage & JSXBase.HTMLAttributes<HTMLBotChatMessageElement>;
            "chat-fab": LocalJSX.ChatFab & JSXBase.HTMLAttributes<HTMLChatFabElement>;
            "chat-input": LocalJSX.ChatInput & JSXBase.HTMLAttributes<HTMLChatInputElement>;
            "chat-messages": LocalJSX.ChatMessages & JSXBase.HTMLAttributes<HTMLChatMessagesElement>;
            "humaine-chatbot": LocalJSX.HumaineChatbot & JSXBase.HTMLAttributes<HTMLHumaineChatbotElement>;
            "system-chat-message": LocalJSX.SystemChatMessage & JSXBase.HTMLAttributes<HTMLSystemChatMessageElement>;
            "user-chat-message": LocalJSX.UserChatMessage & JSXBase.HTMLAttributes<HTMLUserChatMessageElement>;
        }
    }
}
